const data = {
  danGrades: [
    {
      COUNTRY: "ARMENIA",
      NAME: "ERIK MNATSAKANYAN",
      DAN: "1 DAN",
      DATE: "2017-06-15",
      INSTRUCTOR: "ARTUR MANASYAN",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "LEBEL GERHARD",
      DAN: "1 DAN",
      DATE: "2019-06-01",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "SCHWEIGHOFER MATTHIAS",
      DAN: "1 DAN",
      DATE: "2022-06-19",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "SCHOISENGEYER JONAS",
      DAN: "1 DAN",
      DATE: "2022-06-19",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "TISCH PETER",
      DAN: "2 DAN",
      DATE: "2022-06-19",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "WIESBAUER GERALD",
      DAN: "2 DAN",
      DATE: "2022-06-19",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "ANTON JAEGER",
      DAN: "6 DAN",
      DATE: "2017-12-20",
      INSTRUCTOR: "PRUFUNGSKOMMISSION AKB",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "ROMAN FUCHS",
      DAN: "1 DAN",
      DATE: "2009-28-10",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "HANNES HOLZINGER",
      DAN: "3 DAN",
      DATE: "2009-28-10",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "ATTILA ROZSA",
      DAN: "2 DAN",
      DATE: "2009-28-10",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "ALEXANDER HEVESI",
      DAN: "6 DAN",
      DATE: "2017-06-21",
      INSTRUCTOR: "ÖKV",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "ANTON JAEGER",
      DAN: "5 DAN",
      DATE: "2010-08-01",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "TATJANA SCHULTE",
      DAN: "1 DAN",
      DATE: "2012-12-07",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "MICHAEL TAUSEK",
      DAN: "1 DAN",
      DATE: "2013-04-24",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "ATTILA SZECSENYI",
      DAN: "4 DAN",
      DATE: "2009-07-11",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "ANTON RIEDL",
      DAN: "2 DAN",
      DATE: "2012-06-16",
      INSTRUCTOR: "ALEX HEVESI",
    },
    {
      COUNTRY: "AUSTRIA",
      NAME: "ALEXANDER HEVESI",
      DAN: "5 DAN",
      DATE: "200-12-195",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "STEPHANE MARTINY",
      DAN: "1 DAN",
      DATE: "2017-03-25",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "QUANTIN DECKERS",
      DAN: "2 DAN",
      DATE: "2019-05-04",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "DAVAN CHIEN DAO",
      DAN: "1 DAN",
      DATE: "2021-01-04",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "VINCENT LIBERTIAUX",
      DAN: "3 DAN",
      DATE: "2023-09-09",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "BENOIT DELNEUFCOURT",
      DAN: "4 DAN",
      DATE: "2022-05-22",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "ERIC MANDERLIER",
      DAN: "1 DAN",
      DATE: "2022-05-22",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "HUGUES MALHERBE",
      DAN: "1 DAN",
      DATE: "2014-11-15",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JACQUES PRADEL",
      DAN: "1 DAN",
      DATE: "2019-06-02",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "KIRINA EDONIS PELITERA",
      DAN: "1 DAN",
      DATE: "2021-12-30",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "LEA SEMIGLAZOFF",
      DAN: "1 DAN",
      DATE: "2021-10-21",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "LISA POTTIEZ",
      DAN: "1 DAN",
      DATE: "2021-10-24",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "YANIS DERDOUCHE",
      DAN: "1 DAN",
      DATE: "2021-11-21",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "NOAH BLUMART",
      DAN: "3 DAN",
      DATE: "2021-06-27",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "ALEXANDRA BAKANGIMANA",
      DAN: "4 DAN",
      DATE: "2022-12-18",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "FABRICE DELEDDA",
      DAN: "5 DAN",
      DATE: "2021-11-21",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "IMELDA CABIAS",
      DAN: "5 DAN",
      DATE: "2018-06-03",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JEAN-FRANCOIS HASTIR",
      DAN: "5 DAN",
      DATE: "2022-05-22",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JEAN-PAUL FROIDCOURT",
      DAN: "6 DAN",
      DATE: "2018-06-03",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "CLARISSE LOCOGE",
      DAN: "7 DAN",
      DATE: "2019-06-01",
      INSTRUCTOR: "FFKAMA",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "ROSEMAY LOCOGE",
      DAN: "1 DAN",
      DATE: "2017-05-06",
      INSTRUCTOR: "FFKAMA/CLARISSE LOCOGE",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "SYLVAIN TUTTOLOMONDO ",
      DAN: "4 DAN",
      DATE: "2018-10-30",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "STEPHAN SCHOUTERS",
      DAN: "3 DAN",
      DATE: "2018-10-30",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "SEBASTIEN BODART",
      DAN: "1 DAN",
      DATE: "2018-10-30",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "FRANKLIN SIMAIN SATO",
      DAN: "3 DAN",
      DATE: "2018-10-30",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "FRANCIS GASPARD",
      DAN: "2 DAN",
      DATE: "2018-10-30",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "ARTHUR JOSKIN",
      DAN: "1 DAN",
      DATE: "2018-10-30",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JOCELYN JACQUEMIN",
      DAN: "6 DAN",
      DATE: "2017-03-12",
      INSTRUCTOR: "JKF WADOKAI",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "DOMINIQUE DIEU",
      DAN: "1 DAN",
      DATE: "2016-05-14",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JUNIOR AKOTSHI",
      DAN: "3 DAN",
      DATE: "2016-09-28",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "ANOUAR BOUGRINE",
      DAN: "1 DAN",
      DATE: "2016-09-03",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "GHISLAIN SELVAIT",
      DAN: "3 DAN",
      DATE: "2015-05-08",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "MARC SMEETS",
      DAN: "3 DAN",
      DATE: "1988-06-01",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "PASCAL BERNIMONT",
      DAN: "2 DAN",
      DATE: "1997-5-15",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "PASCAL LOUIS",
      DAN: "1 DAN",
      DATE: "1998-05-11",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "OLIVIER SONNET",
      DAN: "1 DAN",
      DATE: "2003-01-06",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "MARC VAN DAMME",
      DAN: "5 DAN",
      DATE: "2013-09-29",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "THIERRY GREFFE",
      DAN: "5 DAN",
      DATE: "2013-09-29",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JEAN MARC JOSKIN",
      DAN: "5 DAN",
      DATE: "2013-09-29",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "GHISLAIN SELVAIT",
      DAN: "2 DAN",
      DATE: "2011-06-04",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "GHISLAIN SELVAIT",
      DAN: "1 DAN",
      DATE: "1997-03-04",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JUNIOR AKOTSHI",
      DAN: "2 DAN",
      DATE: "2013-09-29",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JUNIOR AKOTSHI",
      DAN: "1 DAN",
      DATE: "2009-05-16",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "SYLVAIN TUTTOLOMONDO ",
      DAN: "3 DAN",
      DATE: "2013-09-29",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "SYLVAIN TUTTOLOMONDO ",
      DAN: "2 DAN",
      DATE: "2010-02-20",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "SYLVAIN TUTTOLOMONDO ",
      DAN: "1 DAN",
      DATE: "1998-05-18",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "FRANCIS GASPARD",
      DAN: "1 DAN",
      DATE: "2013-09-29",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JOCELYN JACQUEMIN",
      DAN: "5 DAN",
      DATE: "2011-09-25",
      INSTRUCTOR: "JKF WADOKAI",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "MARC VAN DAMME",
      DAN: "1 DAN",
      DATE: "1990-03-17",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JEAN MARC JOSKIN",
      DAN: "1 DAN",
      DATE: "1985-05-25",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "THIERRY GREFFE",
      DAN: "1 DAN",
      DATE: "1985-06-01",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "MARC VAN DAMME",
      DAN: "2 DAN",
      DATE: "1996-11-01",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JEAN MARC JOSKIN",
      DAN: "2 DAN",
      DATE: "1989-03-10",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "THIERRY GREFFE",
      DAN: "2 DAN",
      DATE: "1995-05-01",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "MARC VAN DAMME",
      DAN: "3 DAN",
      DATE: "2002-10-01",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JEAN MARC JOSKIN",
      DAN: "3 DAN",
      DATE: "1994-05-29",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "THIERRY GREFFE",
      DAN: "3 DAN",
      DATE: "2002-10-01",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "MARC VAN DAMME",
      DAN: "4 DAN",
      DATE: "2008-01-23",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "JEAN MARC JOSKIN",
      DAN: "4 DAN",
      DATE: "2008-01-23",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BELGIUM",
      NAME: "THIERRY GREFFE",
      DAN: "4 DAN",
      DATE: "2008-01-23",
      INSTRUCTOR: "JOCELYN JACQUEMIN",
    },
    {
      COUNTRY: "BOSNIA+HERZEGOVINA",
      NAME: "LUKA BRUS",
      DAN: "1 DAN",
      DATE: "2014-09-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "BOSNIA+HERZEGOVINA",
      NAME: "LJUBOMIR TADIC",
      DAN: "7 DAN",
      DATE: "2014-09-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "CROATIA",
      NAME: "VALENTINA KRISTIC",
      DAN: "1 DAN",
      DATE: "2019-03-30",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "CROATIA",
      NAME: "JOSIP BILIC",
      DAN: "1 DAN",
      DATE: "2019-03-30",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "CROATIA",
      NAME: "ANTUN PUKLAVAC",
      DAN: "2 DAN",
      DATE: "2019-03-30",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "CROATIA",
      NAME: "MARKO JANJIS",
      DAN: "3 DAN",
      DATE: "2019-03-30",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "TOBIAS WÜRTZ HØJBJERG",
      DAN: "3 DAN",
      DATE: "2023-06-24",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MARTIN DAHL",
      DAN: "3 DAN",
      DATE: "2023-06-09",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "THOMAS JENSEN",
      DAN: "3 DAN",
      DATE: "2023-06-09",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "ESTHER MARIE GENEFKE",
      DAN: "1 DAN",
      DATE: "2023-01-30",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "TOM SKOVGAARD JAKOBSEN",
      DAN: "2 DAN",
      DATE: "2022-02-12",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MIKKEL AAHOLM BENNETSEN",
      DAN: "1 DAN",
      DATE: "2022-02-12",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "PHILLIP WERNER PEDERSEN",
      DAN: "2 DAN",
      DATE: "2018-12-08",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MORTEN MARIUS CHRISTIANSEN",
      DAN: "2 DAN",
      DATE: "2018-12-08",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "GUSTAV HOLCK NORMANN",
      DAN: "2 DAN",
      DATE: "2018-12-08",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "FREDERIK ENGHOLM ANDERSEN",
      DAN: "2 DAN",
      DATE: "2018-12-08",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "TOBIAS WÜRTZ HØJBJERG",
      DAN: "2 DAN",
      DATE: "2018-12-08",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "SARAH GRØNLUND JESPERSEN",
      DAN: "1 DAN",
      DATE: "2019-07-29",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "HANNAH GRØNLUND JESPERSEN",
      DAN: "1 DAN",
      DATE: "2019-07-29",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "LUNA HEITMANN",
      DAN: "1 DAN",
      DATE: "2018-10-07",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "ABDUL RAHMAN MARAKEH",
      DAN: "1 DAN",
      DATE: "2018-10-07",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "HENRIK SOEGAARD",
      DAN: "1 DAN",
      DATE: "2018-10-07",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MARTIN DAHL",
      DAN: "2 DAN",
      DATE: "2018-06-01",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "THOMAS JENSEN",
      DAN: "2 DAN",
      DATE: "2018-06-01",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MICHELLE LYSDAL",
      DAN: "2 DAN",
      DATE: "2018-06-01",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "TOM JAKOBSEN",
      DAN: "1 DAN",
      DATE: "2018-06-01",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "JONAS GRUNDT",
      DAN: "1 DAN",
      DATE: "2017-05-20",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "AABO OLSEN SOFIE",
      DAN: "1 DAN",
      DATE: "2014-12-06",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MARTIN DAHL",
      DAN: "1 DAN",
      DATE: "2015-12-09",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "THOMAS LORENTS DENSEN",
      DAN: "1 DAN",
      DATE: "2015-12-09",
      INSTRUCTOR: "RUUD DE VRIES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "BENJAMIN HVISBERG BRIX",
      DAN: "1 DAN",
      DATE: "2012-12-08",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "FLEMMING RANTZAU ALMTORP",
      DAN: "6 DAN",
      DATE: "2014-06-14",
      INSTRUCTOR: "ROB ZWARTJES",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "CHARLOTTE RANTZAU ALMTORP",
      DAN: "2 DAN",
      DATE: "2014-06-14",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "IRAJ HOSEINI",
      DAN: "2 DAN",
      DATE: "2014-06-14",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "SØREN FREDBERG WEISS",
      DAN: "1 DAN",
      DATE: "2014-06-14",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MATHIAS TOKKESDAL HENRIKSEN",
      DAN: "1 DAN",
      DATE: "2014-06-14",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "VALDEMAR JØRGENSEN",
      DAN: "1 DAN",
      DATE: "2014-06-14",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "DIANA NORGAARD MADSEN",
      DAN: "1 DAN",
      DATE: "2011-06-25",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MICHAEL CHRISTOPHER ZIMMERMAN",
      DAN: "2 DAN",
      DATE: "2011-06-25",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MIKKJAL SUNE CHRISTENSEN",
      DAN: "1 DAN",
      DATE: "2011-06-25",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "LASSE DALLERUP",
      DAN: "1 DAN",
      DATE: "2010-12-01",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "SIGNE SAHLERTZ",
      DAN: "1 DAN",
      DATE: "2011-06-25",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "LISBETH HEDE",
      DAN: "1 DAN",
      DATE: "2011-06-25",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MATHIAS LAUSTSEN",
      DAN: "1 DAN",
      DATE: "2010-12-11",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "PETER BROBERG",
      DAN: "1 DAN",
      DATE: "2010-12-11",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "IRAJ HOSEINI",
      DAN: "1 DAN",
      DATE: "2009-06-27",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MIKKEL HOU MOLLER",
      DAN: "1 DAN",
      DATE: "2009-06-27",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "LARS WEJE HANGSTRUP",
      DAN: "1 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "PETER SKIBSTED",
      DAN: "3 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MICHAEL KRABBE",
      DAN: "3 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "OLE BIRGER HANSEN",
      DAN: "1 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "FLEMMING ALMTORP",
      DAN: "5 DAN",
      DATE: "199-12-088",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "CHARLOTTE RANTZAU ALMTORP",
      DAN: "1 DAN",
      DATE: "2008-06-21",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "BJARKE BRISSON NIELSEN",
      DAN: "1 DAN",
      DATE: "2009-12-05",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "DENNIS M.JENSEN",
      DAN: "1 DAN",
      DATE: "2009-06-27",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "BJARKE ANDREASEN ",
      DAN: "1 DAN",
      DATE: "2009-06-27",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "HENRIETTE RANTZAU ALMTORP",
      DAN: "2 DAN",
      DATE: "2009-06-27",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "HELMUT ERNST",
      DAN: "1 DAN",
      DATE: "1997-07-23",
      INSTRUCTOR: "FLEMMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "RUUD DE VRIES",
      DAN: "2 DAN",
      DATE: "2006-09-14",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "MARIE BROBERG",
      DAN: "1 DAN",
      DATE: "2009-06-27",
      INSTRUCTOR: "FLEMING ALMTORP",
    },
    {
      COUNTRY: "DENMARK",
      NAME: "AGUST LUC SKJODT",
      DAN: "1 DAN",
      DATE: "2008-06-21",
      INSTRUCTOR: "FLEMING ALMTORP",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "KATE HAUXWELL",
      DAN: "1 DAN",
      DATE: "2023-04-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "STEWART RATCLIFFE",
      DAN: "1 DAN",
      DATE: "2023-04-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "RHYS MORGAN",
      DAN: "1 DAN",
      DATE: "2023-04-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ASA PARKER",
      DAN: "1 DAN",
      DATE: "2023-04-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ANDREW NEEDHAM",
      DAN: "2 DAN",
      DATE: "2023-04-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "STUART HAUXWELL",
      DAN: "2 DAN",
      DATE: "2023-04-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "OLIVER MC HUGH",
      DAN: "6 DAN",
      DATE: "2023-04-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MARTIN NULTY",
      DAN: "6 DAN",
      DATE: "2023-04-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "BARRY WELCH ",
      DAN: "6 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JASON WALTON",
      DAN: "4 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "RICHARD BAKER",
      DAN: "4 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MAGGY JENNINGS",
      DAN: "4 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MATTHEW WOOD ",
      DAN: "3 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ROBERT BARRETT",
      DAN: "3 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JACK FRANKLIN",
      DAN: "3 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "QUAN NGUYEN",
      DAN: "1 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JASON KELLY",
      DAN: "2 DAN",
      DATE: "2019-04-05",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "SIMON KAY",
      DAN: "1 DAN",
      DATE: "2019-04-05",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "NIGEL BLACKMAN",
      DAN: "2 DAN",
      DATE: "2019-04-05",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "DAVID BAKER",
      DAN: "1 DAN",
      DATE: "2019-04-05",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "NATASHA MC MINN",
      DAN: "1 DAN",
      DATE: "2017-08-04",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "CONNIE CHAND",
      DAN: "6 DAN",
      DATE: "2017-10-04",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JASON WALTON",
      DAN: "3 DAN",
      DATE: "2017-05-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "RICHARD BAKER",
      DAN: "3 DAN",
      DATE: "2017-05-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "STEPHEN SINGLETON",
      DAN: "3 DAN",
      DATE: "2017-05-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MAGGY JENNINGS",
      DAN: "3 DAN",
      DATE: "2017-05-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "GARY MOIR",
      DAN: "2 DAN",
      DATE: "2017-05-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "BRIAN HAYES",
      DAN: "7 DAN",
      DATE: "2016-11-07",
      INSTRUCTOR: "WADOKAI EUROPE COMMITTEE",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JACK FRANKLIN",
      DAN: "2 DAN",
      DATE: "2016-11-10",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "OLIVER MC HUGH",
      DAN: "4 DAN",
      DATE: "2015-05-13",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JASON WALTON",
      DAN: "2 DAN",
      DATE: "2015-02-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "RICHARD BAKER",
      DAN: "2 DAN",
      DATE: "2015-02-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ROBERT BARRETT",
      DAN: "2 DAN",
      DATE: "2015-02-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "TONY STANNARD",
      DAN: "1 DAN",
      DATE: "2015-02-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ANDREW NEEDHAM",
      DAN: "1 DAN",
      DATE: "2015-02-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "RUBY FRANKLIN",
      DAN: "1 DAN",
      DATE: "2015-02-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JACK FRANKLIN",
      DAN: "1 DAN",
      DATE: "2010-05-30",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "CHLOE THORNE",
      DAN: "1 DAN",
      DATE: "2013-09-22",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "STEVE GRANT",
      DAN: "3 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ELIZABETH MARCUS",
      DAN: "1 DAN",
      DATE: "2013-09-29",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "BARRY WILKINSON",
      DAN: "8 DAN",
      DATE: "2013-04-07",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "PETER KYLE",
      DAN: "2 DAN",
      DATE: "2012-11-03",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MARY MARCUS",
      DAN: "1 DAN",
      DATE: "2012-11-03",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "TOMMY MARRETT",
      DAN: "4 DAN",
      DATE: "2012-11-03",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MARTIN NULTY",
      DAN: "3 DAN",
      DATE: "2012-11-03",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "OLIVER MC HUGH",
      DAN: "3 DAN",
      DATE: "2012-11-03",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "CHRISTOPHER ROBINSON",
      DAN: "2 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JAKE FAIRBROTHER",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "JAMIE BOYT",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ALISON PEARCE",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "EMMA BURNISTON",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "DAVE THORNE",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "EMILY COATES",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ADAM COATES",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "GEORGE STEVENS",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "CAITLIN RICH",
      DAN: "1 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "DANIEL PEACH",
      DAN: "2 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "EMILY PEACH",
      DAN: "2 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ANN RICH",
      DAN: "2 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "SAMATHA BURNISTON",
      DAN: "2 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "STEVE GRANT",
      DAN: "2 DAN",
      DATE: "2013-09-01",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "TINA HARRISON",
      DAN: "4 DAN",
      DATE: "2005-03-18",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ROGER STEELE",
      DAN: "1 DAN",
      DATE: "2009-09-18",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MELINA MUKHERGEE",
      DAN: "1 DAN",
      DATE: "2009-09-18",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "SCOTT BUTTLER",
      DAN: "1 DAN",
      DATE: "2009-09-18",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "SIMON SHERWOOD",
      DAN: "1 DAN",
      DATE: "2009-09-18",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "REBECCA MORELAND",
      DAN: "1 DAN",
      DATE: "2009-09-18",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MARCUS YEATMAN",
      DAN: "4 DAN",
      DATE: "2009-09-18",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "NICHOLAS PERKINS",
      DAN: "4 DAN",
      DATE: "2005-03-18",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "ZOE TAYLOR",
      DAN: "1 DAN",
      DATE: "2006-01-17",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "BARRY DUKE",
      DAN: "1 DAN",
      DATE: "2003-05-30",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "BARRY WILKINSON",
      DAN: "7 DAN",
      DATE: "2001-09-16",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "ESTONIA",
      NAME: "ALAR JAANUS",
      DAN: "1 DAN",
      DATE: "2013-11-01",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "ESTONIA",
      NAME: "MADIS SINIMETS",
      DAN: "4 DAN",
      DATE: "2013-11-01",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "ESTONIA",
      NAME: "KAJAR HELP",
      DAN: "3 DAN",
      DATE: "2013-11-01",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "ESTONIA",
      NAME: "HEILI JÄRV",
      DAN: "2 DAN",
      DATE: "2012-11-02",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "ESTONIA",
      NAME: "MAIRO KULLISAAR",
      DAN: "1 DAN",
      DATE: "2012-11-02",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "FINLAND",
      NAME: "YRSA LINDQUIST",
      DAN: "5 DAN",
      DATE: "200-11-111",
    },
    {
      COUNTRY: "FRANCE",
      NAME: "PATRICE BELRHITI",
      DAN: "9 DAN",
      DATE: "2018-11-17",
      INSTRUCTOR: "FFKAMA",
    },
    {
      COUNTRY: "FRANCE",
      NAME: "DIDIER PERRIN",
      DAN: "6 DAN",
      DATE: "2009-12-27",
      INSTRUCTOR: "PATRICE BELRHITI",
    },
    {
      COUNTRY: "FRANCE",
      NAME: "GILLES IHLE",
      DAN: "5 DAN",
      DATE: "2008-01-26",
      INSTRUCTOR: "PATRICE BELRHITI",
    },
    {
      COUNTRY: "FRANCE",
      NAME: "PATRICE BELRHITI",
      DAN: "8 DAN",
      INSTRUCTOR: "FFKAMA",
    },
    {
      COUNTRY: "GREECE",
      NAME: "KALIOPI-IOANNA KYPSELIDOU",
      DAN: "1 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "MARIANNA PAVLAKI",
      DAN: "1 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "ANTONIOS PAPADOPOULOS",
      DAN: "1 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "VASILISA TSYPLAKOVA",
      DAN: "1 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "MARIA-GEORGIA ANASTASIOU",
      DAN: "1 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "ANASTASIA-AGGELIKI CHATZILAMPROU",
      DAN: "1 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "CHRISTINA-ANNA STAKTEA",
      DAN: "1 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "ARGYRO SKARLI",
      DAN: "2 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "DIOGENIS KYPSELIDIS",
      DAN: "3 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "CHRISTOS KARIOTIS",
      DAN: "3 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "GREECE",
      NAME: "GEORGIOS MARKAKOS",
      DAN: "4 DAN",
      DATE: "2019-03-12",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "FRANCOIS BICHEL",
      DAN: "7 DAN",
      DATE: "2022-04-07",
      INSTRUCTOR: "FLAM",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "CLAUDINE LEYERS",
      DAN: "6 DAN",
      DATE: "2022-04-07",
      INSTRUCTOR: "FLAM",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "NORBERT SCHMIT",
      DAN: "4 DAN",
      DATE: "2022-04-07",
      INSTRUCTOR: "FLAM",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "TAMARA SCHUH",
      DAN: "5 DAN",
      DATE: "2022-04-07",
      INSTRUCTOR: "FLAM",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "EZIO DE RUBEIS",
      DAN: "2 DAN",
      DATE: "2021-11-06",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "DAVID SCHMIT",
      DAN: "1 DAN",
      DATE: "2020-11-14",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "SEBASTIEN TERLICA",
      DAN: "1 DAN",
      DATE: "2020-11-14",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "SAM KIRSCH",
      DAN: "1 DAN",
      DATE: "2020-11-14",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "MARIANA DE AMORIM",
      DAN: "1 DAN",
      DATE: "2020-11-14",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "LEONI ALIBASIC",
      DAN: "1 DAN",
      DATE: "2020-11-14",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "CHIARA SCHUMANN",
      DAN: "1 DAN",
      DATE: "2020-11-14",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "CLAUDINE LEYERS",
      DAN: "5 DAN",
      DATE: "2015-07-05",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "FRANCOIS BICHEL",
      DAN: "6 DAN",
      DATE: "2015-07-05",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "ANDRE BICHEL",
      DAN: "2 DAN",
      DATE: "2015-02-07",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "NORBERT SCHMIT",
      DAN: "3 DAN",
      DATE: "2014-11-15",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "MAGALI JACOB",
      DAN: "3 DAN",
      DATE: "2014-11-15",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "DINO SABOTIC",
      DAN: "1 DAN",
      DATE: "2014-10-23",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "LETIZIA SCHLIM",
      DAN: "1 DAN",
      DATE: "2014-10-23",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "DOMINIQUE DELACRE",
      DAN: "1 DAN",
      DATE: "2014-10-23",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "SABRINA DOS SANTOS",
      DAN: "1 DAN",
      DATE: "2014-10-23",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "ILDA SABOTIC",
      DAN: "1 DAN",
      DATE: "2013-10-30",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "TAMARA SCHUH",
      DAN: "4 DAN",
      DATE: "2013-07-12",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "CLAUDINE LEYERS",
      DAN: "4 DAN",
      DATE: "2009-07-12",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "TAMARA SCHUH",
      DAN: "3 DAN",
      DATE: "2009-07-12",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "ALDEN SUNTIC",
      DAN: "1 DAN",
      DATE: "2009-07-12",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "FRANCOIS BICHEL",
      DAN: "5 DAN",
      DATE: "2009-01-04",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "NORBERT SCHMIT",
      DAN: "2 DAN",
      DATE: "2009-03-28",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "JEAN-NICOLAS BOURTEMBOURG",
      DAN: "2 DAN",
      DATE: "2009-03-28",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "MAGALI JACOB",
      DAN: "2 DAN",
      DATE: "2009-03-28",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "PATRICK CORNARO",
      DAN: "1 DAN",
      DATE: "2009-03-28",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "ANDRE BICHEL",
      DAN: "1 DAN",
      DATE: "2009-03-28",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "JEAN-NICOLAS BOURTEMBOURG",
      DAN: "1 DAN",
      DATE: "2005-02-12",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "MAGALI JACOB",
      DAN: "1 DAN",
      DATE: "2006-12-09",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "PIERRE ETSCHEID",
      DAN: "2 DAN",
      DATE: "2002-12-21",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "TAMARA SCHUH",
      DAN: "2 DAN",
      DATE: "2002-12-21",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "TAMARA SCHUH",
      DAN: "1 DAN",
      DATE: "1999-11-28",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "NORBERT SCHMIT",
      DAN: "1 DAN",
      DATE: "1997-05-25",
      INSTRUCTOR: "FRANCOIS BICHEL",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "CLAUDINE LEYERS",
      DAN: "3 DAN",
      DATE: "1991-04-21",
      INSTRUCTOR: "KAMIGAITO YOSHIKAZU",
    },
    {
      COUNTRY: "LUXEMBOURG",
      NAME: "FRANCOIS BICHEL",
      DAN: "4 DAN",
      DATE: "1991-04-21",
      INSTRUCTOR: "KAMIGAITO YOSHIKAZU",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "SILVESTER BAKKER",
      DAN: "1 DAN",
      DATE: "2023-06-29",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "RUUD DE VRIES",
      DAN: "6 DAN",
      DATE: "2023-06-10",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "D.DONA",
      DAN: "1 DAN",
      DATE: "2022-12-10",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "D.D.LAMERS",
      DAN: "2 DAN",
      DATE: "2022-12-10",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "A.P.G. VAN DORT",
      DAN: "3 DAN",
      DATE: "2022-12-10",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "F.J. VAN VEEN",
      DAN: "5 DAN",
      DATE: "2022-07-02",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "L.J.M.FLOHR",
      DAN: "4 DAN",
      DATE: "2022-07-02",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "P.J.D.N DRIESSEN",
      DAN: "4 DAN",
      DATE: "2022-07-02",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "H.H. MEENTS",
      DAN: "6 DAN",
      DATE: "2022-07-02",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "U.MASSEE",
      DAN: "1 DAN",
      DATE: "1992-12-20",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "B.S. SCHOOLAERT",
      DAN: "1 DAN",
      DATE: "2022-07-02",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "Y.AZIZI",
      DAN: "4 DAN",
      DATE: "2022-07-02",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "M.SPITS",
      DAN: "5 DAN",
      DATE: "2022-07-02",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "YAHYA AZIZI",
      DAN: "3 DAN",
      DATE: "2020-02-18",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "HARM MASSEE",
      DAN: "8 DAN",
      DATE: "2018-11-17",
      INSTRUCTOR: "WADOKAI NETHERLANDS",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "P.J.D.N DRIESSEN",
      DAN: "3 DAN",
      DATE: "2018-12-01",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "G.VAN DER DUNGEN",
      DAN: "3 DAN",
      DATE: "2018-12-01",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "L.J.M.FLOHR",
      DAN: "3 DAN",
      DATE: "2018-12-01",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "RUUD DE VRIES",
      DAN: "5 DAN",
      DATE: "2018-06-01",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "A.P.G. VAN DORT",
      DAN: "2 DAN",
      DATE: "2017-10-28",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "H.TIEMENS",
      DAN: "2 DAN",
      DATE: "2017-10-28",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "K.MORSINK",
      DAN: "2 DAN",
      DATE: "2017-10-28",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "A.G. BASTIAAN",
      DAN: "1 DAN",
      DATE: "2017-10-28",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "HENK LEENDERT SPORKSLEDE",
      DAN: "5 DAN",
      DATE: "2016-10-01",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "MARINUS MORSINK",
      DAN: "4 DAN",
      DATE: "2016-10-01",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "RUUD DE VRIES",
      DAN: "4 DAN",
      DATE: "2016-06-18",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "MICHAELS SPITS",
      DAN: "4 DAN",
      DATE: "2015-06-06",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "DANNY EDGAR VAN DER VUURST",
      DAN: "1 DAN",
      DATE: "2015-06-06",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "PETER DRIESSEN",
      DAN: "1 DAN",
      DATE: "1987-03-01",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "KLAAS MORSINK",
      DAN: "1 DAN",
      DATE: "1992-06-13",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "GERARD VAN DEN DRUNGEN",
      DAN: "1 DAN",
      DATE: "1986-03-02",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "ECO KLEEFSTRA",
      DAN: "3 DAN",
      DATE: "2013-06-22",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "MARINUS MORSINK",
      DAN: "3 DAN",
      DATE: "1998-06-06",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "MICHAEL SPITS",
      DAN: "3 DAN",
      DATE: "2011-11-21",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "MICHAEL VAN DER NULFT",
      DAN: "4 DAN",
      DATE: "2012-11-24",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "HARRY MEENTS",
      DAN: "4 DAN",
      DATE: "2010-06-06",
      INSTRUCTOR: "HARM MASSE",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "ALEXIS BROUWER",
      DAN: "7 DAN",
      DATE: "2008-11-30",
      INSTRUCTOR: "KONO",
    },
    {
      COUNTRY: "NETHERLANDS",
      NAME: "HARM MASSEE",
      DAN: "7 DAN",
      DATE: "2009-03-15",
      INSTRUCTOR: "KONO+SUZUKI",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "GONCALO BRANCO",
      DAN: "2 DAN",
      DATE: "2015-04-11",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "JOAO SANTOS",
      DAN: "1 DAN",
      DATE: "2015-04-11",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "JORGE MANUEL RODRIGUES",
      DAN: "1 DAN",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "JOAO HIPOLITO JANUARIO",
      DAN: "1 DAN",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "PEDRO MIGUEL TEIXEIRA",
      DAN: "2 DAN",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "LUIS ESPIRITO SANTO",
      DAN: "3 DAN",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "LUIS PAULO BARBAS",
      DAN: "3 DAN",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "LUIS TOME SANTOS",
      DAN: "6 DAN",
      DATE: "2011-04-09",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "MARCO BRANCO",
      DAN: "3 DAN",
      DATE: "2011-04-09",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "LUIS ESPIRITO SANTO",
      DAN: "2 DAN",
      DATE: "2011-04-09",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "LUIS PAULO BARBAS",
      DAN: "2 DAN",
      DATE: "2011-04-09",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "BRUNO MORGADO",
      DAN: "1 DAN",
      DATE: "2011-04-09",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "PORTUGAL",
      NAME: "GONCALO BRANCO",
      DAN: "1 DAN",
      DATE: "2011-04-09",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CIUCA PETRICA",
      DAN: "1 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CIUCA ION",
      DAN: "1 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "PALMA ALEXANDRU",
      DAN: "2 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "ANDRADE CONCEICAO DIONISIO",
      DAN: "4 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "RADU MIHAI",
      DAN: "3 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "JIEANU COSMIN HORATIU",
      DAN: "5 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "DUMITRESCU VASILE",
      DAN: "5 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "MESINSCHI MARIAN",
      DAN: "3 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "MOLDOVAN ADRIAN",
      DAN: "4 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "GOMES RODRIGUES PEDRO",
      DAN: "6 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "LIPIANU BOGDAN",
      DAN: "4 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "KENICHIRO ABE",
      DAN: "7 DAN",
      DATE: "2019-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "SABINO FREDERICO DA LUZ TAVARES",
      DAN: "7 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "MARIO ROBERT DAMIAN",
      DAN: "1 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CEZAR CRISTEA",
      DAN: "5 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "RADU ALEXANDRU TODIRAS",
      DAN: "3 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "DARIUS MARIAN MANEA",
      DAN: "1 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "RADU DANUT CIUCA",
      DAN: "5 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "GEORGINA E. TINCA",
      DAN: "3 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "LAURA ANGHELINICI",
      DAN: "1 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "SORIN ALEXANDRU BURTAN",
      DAN: "2 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CRISTIAN ROBERT DUMITRU",
      DAN: "2 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "ANDREI FODAI",
      DAN: "1 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "ANDRA NOVITCHI",
      DAN: "2 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "MOHAMED AL RIFAE",
      DAN: "5 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CRISTIAN IULIUS NICULAE",
      DAN: "3 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "ALINA PATRU",
      DAN: "3 DAN",
      DATE: "2014-07-06",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "ADALBERTO SANTOS COELHO",
      DAN: "4 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "RASIU ANA",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CHELES CLAUDIU",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CHELES IULIAN",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "MICU VERONICA",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "RADU MIHAI",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "STANCIU MIHAELA",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "SEULESCU CRISTINA",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "SAVIN FLORIN",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "BIDINA ANDREI",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "POPESCU MIHAELA",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "MIHALACHE IOANA",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "TOTH CORNEL",
      DAN: "1 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CASIAN GINA",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "BIDINA ANDRADA",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "TINCA GEORGIANA",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "PANDIA MARINA",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "SOARE ALINA",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "GHEORGHE FLORIAN",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CARCIU SORIN",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "FUSARU DANIEL",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CUCU RADU",
      DAN: "2 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "COCORA CRISTIAN",
      DAN: "2 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "FRANCOISE P. TAVARES",
      DAN: "2 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CIUCA RADU-DANUT",
      DAN: "2 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "ANCAS LAURENTIU",
      DAN: "2 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "VIZITEU DORIN-GELU",
      DAN: "2 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "RADU ADRIAN",
      DAN: "2 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "TODIRAS RADU",
      DAN: "2 DAN",
      DATE: "2005-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "PATRU MARIA LUMINITA",
      DAN: "3 DAN",
      DATE: "2002-04-09",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "LIPIANU BOGDAN",
      DAN: "3 DAN",
      DATE: "2002-04-14",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "PATRU AUREL",
      DAN: "4 DAN",
      DATE: "2002-04-14",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "JOSE C. GOMES MONTEIRO",
      DAN: "4 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "IONICA M. SORIN",
      DAN: "4 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "DUMITRESCU VASILE",
      DAN: "4 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "CRISTEA CESAR",
      DAN: "4 DAN",
      DATE: "2003-04-04",
      INSTRUCTOR: "SABINO FREDERICO DA LUZ TAVARES",
    },
    {
      COUNTRY: "ROMANIA",
      NAME: "SABINO FREDERICO DA LUZ TAVARES",
      DAN: "6 DAN",
      DATE: "200-04-043",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "COLIN SMITH",
      DAN: "4 DAN",
      DATE: "2023-04-30",
      INSTRUCTOR: "ADAM HAMISH",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "COLIN CLAPPERTON ",
      DAN: "8 DAN",
      DATE: "2010-03-10",
      INSTRUCTOR: "SKF",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "BARRY DOUGLAS",
      DAN: "1 DAN",
      DATE: "2011-03-26",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "SARAH MC MILLAN",
      DAN: "2 DAN",
      DATE: "2011-03-26",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CAMERON J. COLLINS",
      DAN: "1 DAN",
      DATE: "2011-03-26",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "DOLLAR MILLAR",
      DAN: "1 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "SHAWNISAY MILLAR",
      DAN: "1 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "OLIVER MC HUGH",
      DAN: "6 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "ENGLAND",
      NAME: "MARTIN NULTY",
      DAN: "6 DAN",
      DATE: "2022-03-28",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "COURTNEY SZABO",
      DAN: "1 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "OLIVIA VICKY HAND",
      DAN: "1 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "REBECCA CRAIG",
      DAN: "1 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CONNOR RAE BELL",
      DAN: "1 DAN",
      DATE: "2010-06-12",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "ALISTAIR MAC RAE",
      DAN: "1 DAN",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "PETER WILSON",
      DAN: "1 DAN",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "JOHN MC FARLANE",
      DAN: "1 DAN",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CAROLINE MC FARLANE",
      DAN: "1 DAN",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "ROBERT HINTON",
      DAN: "1 DAN",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "GAVIN MC KAY",
      DAN: "1 DAN",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "ROSS MOYES",
      DAN: "???",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "JAMIE GREEN",
      DAN: "1 DAN",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "ELISABETH MARY QUINLAN",
      DAN: "1 DAN",
      DATE: "2009-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "JAMIE BRADLEY",
      DAN: "1 DAN",
      DATE: "2009-03-21",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CAITLYN REEDER",
      DAN: "1 DAN",
      DATE: "2008-11-22",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "SCOTT BRADLEY",
      DAN: "1 DAN",
      DATE: "2008-11-22",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "SARAH MURPHY",
      DAN: "1 DAN",
      DATE: "2008-11-22",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "ANGUS CONNOR",
      DAN: "1 DAN",
      DATE: "2008-11-22",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "PAUL CONNOR",
      DAN: "3 DAN",
      DATE: "2006-06-24",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "SARAH MC MILLAN",
      DAN: "1 DAN",
      DATE: "2008-11-22",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "DOROTHY BRADLEY",
      DAN: "1 DAN",
      DATE: "2008-06-07",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "JOHN CROZIER",
      DAN: "1 DAN",
      DATE: "2007-11-24",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CHLOE MC LEAN",
      DAN: "2 DAN",
      DATE: "2007-11-24",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "THOMAS MC LELLAND",
      DAN: "2 DAN",
      DATE: "2005-03-20",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "GARY KIRKWOOD",
      DAN: "1 DAN",
      DATE: "2006-11-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "MATTHEW TAINSH",
      DAN: "1 DAN",
      DATE: "2007-03-24",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "STEVEN COLLINS",
      DAN: "1 DAN",
      DATE: "2007-03-24",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "MELISSA GILLIES",
      DAN: "1 DAN",
      DATE: "2007-03-24",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "HARRY OLIFF",
      DAN: "1 DAN",
      DATE: "2004-03-24",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "ROBERT MC FARLANE",
      DAN: "1 DAN",
      DATE: "2006-11-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "GAYNOR BOUGHEY",
      DAN: "1 DAN",
      DATE: "2004-11-27",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CHARLES EARNSHAW",
      DAN: "1 DAN",
      DATE: "2006-06-24",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "IRINA EARNSHAW",
      DAN: "1 DAN",
      DATE: "2004-06-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "IONA FROST",
      DAN: "1 DAN",
      DATE: "2004-06-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "KAREN WOOD",
      DAN: "1 DAN",
      DATE: "2006-11-18",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "ERIC WOOD",
      DAN: "3 DAN",
      DATE: "2004-06-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CHARLES ROBINSON",
      DAN: "1 DAN",
      DATE: "2004-06-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "MARK MC COOL",
      DAN: "4 DAN",
      DATE: "2006-04-23",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "MICHAEL MC HUGH",
      DAN: "1 DAN",
      DATE: "2006-11-18",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "LESLIE CAIRNS",
      DAN: "4 DAN",
      DATE: "2006-06-28",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "WILLIAM CAMERON ",
      DAN: "1 DAN",
      DATE: "2006-11-18",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "COLIN RUSSELL",
      DAN: "3 DAN",
      DATE: "1998-11-14",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CONNOR MC LEOD",
      DAN: "1 DAN",
      DATE: "2006-11-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "HARRY LAWRIE",
      DAN: "1 DAN",
      DATE: "2006-11-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "STEVEN WYLLIE",
      DAN: "1 DAN",
      DATE: "2006-11-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "MARK WYLLIE",
      DAN: "1 DAN",
      DATE: "2006-11-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "PETER GARDNER",
      DAN: "3 DAN",
      DATE: "2006-11-19",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "CHARLES LINDSAY",
      DAN: "6 DAN",
      DATE: "2006-04-23",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "ERIN MORTAGH",
      DAN: "1 DAN",
      DATE: "2006-11-18",
      INSTRUCTOR: "COLIN CLAPPERTON",
    },
    {
      COUNTRY: "SCOTLAND",
      NAME: "COLIN CLAPPERTON ",
      DAN: "7 DAN",
      DATE: "2002-06-02",
      INSTRUCTOR: "SKF",
    },
    {
      COUNTRY: "SWEDEN",
      NAME: "SHINGO OHGAMI",
      DAN: "7 DAN",
      DATE: "199-06-301",
    },
    {
      COUNTRY: "SWITZERLAND",
      NAME: "ROMANO PIANI",
      DAN: "4 DAN",
      DATE: "2016-11-10",
      INSTRUCTOR: "WADOKAI EUROPE JURY",
    },
    {
      COUNTRY: "SWITZERLAND",
      NAME: "DANIEL HUMBEL",
      DAN: "6 DAN",
      DATE: "200-08-215",
    },
    {
      COUNTRY: "WALES",
      NAME: "JASON HAYWARD",
      DAN: "5 DAN",
      DATE: "2023-10-20",
      INSTRUCTOR: "BARRY WILKINSON",
    },
    {
      COUNTRY: "WALES",
      NAME: "PAUL SCOTT",
      DAN: "6 DAN",
      DATE: "2014-04-27",
      INSTRUCTOR: "PAUL SCOTT",
    },
  ],
};
module.exports = data;
